### ISSUE TITLE
cannot build using --features "metal" due to `cargo` limitations

### ISSUE THREAD

**Issue by tsal** [amethyst/grumpy_visitors#25]
see https://github.com/rust-lang/cargo/issues/5015

**Comment by tsal** [comment]
never mind; looks like this is pinned to use vulkan.

**Comment by vladbat00** [comment]
@tsal, hi, you can actually build this for metal, but you need to uncomment these lines in `Cargo.toml`:
https://github.com/amethyst/grumpy_visitors/blob/master/bins/client/Cargo.toml#L38-L40
and make sure to comment out vulkan then. Yeah, this is indeed not the most convenient way to do it.. :(

Also related: https://github.com/rust-lang/cargo/issues/1197.
