### ISSUE TITLE
Implement a new UI widget for modal dialogs

### ISSUE THREAD

**Issue by vladbat00** [amethyst/grumpy_visitors#31]

**Comment by erlend-sh** [comment]
Is this strictly for error/debugging widgets? Then imgui will probably suffice?

**Comment by vladbat00** [comment]
@erlend-sh no, this is intended to be an actual part of UI. There're some scenarios when an error/warning message should be shown to a user, like "Couldn't connect to a server" (more examples here #33). I believe most of them will be related to networking.
